import type {Metadata} from "next";

// font
import {Noto_Sans_KR} from "next/font/google";

// style
import "./globals.css";

// components
import {AuroraBackground} from "@/components/ui/aurora-background";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const noto_sans_kr = Noto_Sans_KR({subsets: ["latin"]});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${noto_sans_kr.className} antialiased`}>
        <AuroraBackground>{children}</AuroraBackground>
      </body>
    </html>
  );
}
