import type {Metadata} from "next";

// font
import {Noto_Sans_KR} from "next/font/google";

// style
import "./globals.css";

// context
import {AuroraBackgroundProvider} from "@/components/context/AuroraBackgroundProvider";
import SmoothScrollProvider from "@/components/context/SmoothScrollProvider";
import {ThemeProvider} from "@/components/context/theme-provider";
import {ClientProvider} from "@/components/context/ClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // openGraph: {
  //   title: blogName,
  //   description: blogDesc,
  //   siteName: blogName,
  //   images: '/posts/backend/nest_js_4_thumbnail.png',
  //   type: 'website',
  // },
};

const noto_sans_kr = Noto_Sans_KR({subsets: ["latin"]});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${noto_sans_kr.className} antialiased`}>
        <ThemeProvider attribute="class" enableSystem={true}>
          <ClientProvider>
            <SmoothScrollProvider />
            <AuroraBackgroundProvider>{children}</AuroraBackgroundProvider>
          </ClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
